- name: Render.com Deploy
  # You may pin to the exact commit or the version.
  # uses: ttskch/render-deploy@e4235ddbf689a8d932449f15b8f9b586cc61d6b6
  uses: ttskch/render-deploy@v1.0.0
  with:
    # Render.com API key
    api-key: rnd_GnYhj7R7Ve7F0Me6PXAjBmM3L5cm
    # ID of the service to deploy
    service-id: srv-ckabakugtj9c73aopas0
    # Interval to check deploy status (sec)
    interval: 10 # optional, default is 10
    # If deploy has not finished after this time, the action will fail (sec)
    timeout: 600 # optional, default is 600
