name: Render
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [19.8.1]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3 # was "v2" before 
        with: 
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # was "v2" before
        with: 
          node-version: ${{ matrix.node-version }}

      - name: PNPM install, build
        run: |
          npm install pnpm -g
          pnpm run
          pnpm i
          pnpm build
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
